// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANgELY9-UoSGm7-6zd0GheGxDWYpkzPEk',
    appId: '1:185267665680:web:7a9e154623e41b4a610395',
    messagingSenderId: '185267665680',
    projectId: 'ja-connect-2035d',
    authDomain: 'ja-connect-2035d.firebaseapp.com',
    storageBucket: 'ja-connect-2035d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuiKP9kh5y6_090m_OLK7y0j4szpjtGFY',
    appId: '1:185267665680:android:f8b70439f41bc366610395',
    messagingSenderId: '185267665680',
    projectId: 'ja-connect-2035d',
    storageBucket: 'ja-connect-2035d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI9pZNDQeCAOjXedOoId4wwlDRn-wmVEg',
    appId: '1:185267665680:ios:aef8385d815d4085610395',
    messagingSenderId: '185267665680',
    projectId: 'ja-connect-2035d',
    storageBucket: 'ja-connect-2035d.appspot.com',
    iosClientId: '185267665680-m2uo6nvhsqmrn5idu79t9mrncl2h35ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.ninjaConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI9pZNDQeCAOjXedOoId4wwlDRn-wmVEg',
    appId: '1:185267665680:ios:aef8385d815d4085610395',
    messagingSenderId: '185267665680',
    projectId: 'ja-connect-2035d',
    storageBucket: 'ja-connect-2035d.appspot.com',
    iosClientId: '185267665680-m2uo6nvhsqmrn5idu79t9mrncl2h35ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.ninjaConnect',
  );
}
